// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzSuoM_P-GN0t7R30QbSMHYUDfDZTAWA',
    appId: '1:646966465993:web:04821fa5911f342ce80418',
    messagingSenderId: '646966465993',
    projectId: 'emergence44-84472',
    authDomain: 'emergence44-84472.firebaseapp.com',
    storageBucket: 'emergence44-84472.firebasestorage.app',
    measurementId: 'G-LT9G1X12JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOQEnIERwAbaeNm9ogS7WY-EeKRqN31I0',
    appId: '1:646966465993:android:21188d552fcff006e80418',
    messagingSenderId: '646966465993',
    projectId: 'emergence44-84472',
    storageBucket: 'emergence44-84472.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyiDR1RpwLspSqM0Tao9auwZN3YE698Vs',
    appId: '1:646966465993:ios:501ca286317a6fb9e80418',
    messagingSenderId: '646966465993',
    projectId: 'emergence44-84472',
    storageBucket: 'emergence44-84472.firebasestorage.app',
    iosBundleId: 'com.example.emergenceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyiDR1RpwLspSqM0Tao9auwZN3YE698Vs',
    appId: '1:646966465993:ios:501ca286317a6fb9e80418',
    messagingSenderId: '646966465993',
    projectId: 'emergence44-84472',
    storageBucket: 'emergence44-84472.firebasestorage.app',
    iosBundleId: 'com.example.emergenceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgzSuoM_P-GN0t7R30QbSMHYUDfDZTAWA',
    appId: '1:646966465993:web:54473fa7114c4040e80418',
    messagingSenderId: '646966465993',
    projectId: 'emergence44-84472',
    authDomain: 'emergence44-84472.firebaseapp.com',
    storageBucket: 'emergence44-84472.firebasestorage.app',
    measurementId: 'G-QQ3G5CPCS9',
  );
}
